### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by LifeCANvs** [y4my4my4m/Zeal32BitPNGViewer#1]
Very nice! Which license applies to this project?

**Comment by y4my4my4m** [comment]
@LifeCANvs 
I assume some derivative of [uPNG's MIT license](https://github.com/photopea/UPNG.js/blob/master/LICENSE), 
but i took the [uPNG](https://github.com/y4my4my4m/Zeal32BitPNGViewer/blob/master/Lib/uPNG.ZC) from Alec Murphy (a guy who's made a bunch of TempleOS projects who's nowhere to be found online nowadays) and i made a [32bit version](https://github.com/y4my4my4m/Zeal32BitPNGViewer/blob/master/Lib/uPNG32.ZC) of it by modifying it a bit.

I have no idea when does his uPNG code comes from, perhaps it was from a time where it wasn't MIT licensed so it doesn't require any license, maybe it was. I'm not sure.
Which is why I've just continued writing down the copyright and "history" in the code itself.

**Comment by LifeCANvs** [comment]
> @LifeCANvs I assume some derivative of [uPNG's MIT license](https://github.com/photopea/UPNG.js/blob/master/LICENSE), but i took the [uPNG](https://github.com/y4my4my4m/Zeal32BitPNGViewer/blob/master/Lib/uPNG.ZC) from Alec Murphy (a guy who's made a bunch of TempleOS projects who's nowhere to be found online nowadays) and i made a [32bit version](https://github.com/y4my4my4m/Zeal32BitPNGViewer/blob/master/Lib/uPNG32.ZC) of it by modifying it a bit.
> 
> I have no idea when does his uPNG code comes from, perhaps it was from a time where it wasn't MIT licensed so it doesn't require any license, maybe it was. I'm not sure. Which is why I've just continued writing down the copyright and "history" in the code itself.

Thanks for your reply and explanation.
